import { Link, Route, Routes, useParams } from 'react-router-dom'
import Layout from './components/Layout'
import HeroCanvas from './components/HeroCanvas'
import { posts, postBySlug } from './content/posts'
import DemoFrame from './components/DemoFrame'

const SectionLabel = ({ children }) => <div className="eyebrow"><span />{children}</div>
const formatDate = (date) => new Intl.DateTimeFormat('en', { year: 'numeric', month: 'short', day: 'numeric' }).format(new Date(date))

function Home() { const featured = posts.slice(0, 3); return <>
  <section className="hero"><HeroCanvas /><div className="hero-content"><SectionLabel>Computer science · Ljubljana</SectionLabel><h1>Lan Sevčnikar</h1><p>I make computers do stuff — mostly machine learning, data, and the occasional graphics engine.</p><div className="actions"><Link className="button button-primary" to="/blog">Read the blog</Link><Link className="button" to="/portfolio">View portfolio &amp; CV</Link></div></div><div className="scroll-hint"><i />scroll</div></section>
  <section className="section narrow"><SectionLabel>About</SectionLabel><h2>Student, tinkerer, and future data scientist.</h2><div className="copy"><p>I’m a computer science student from Maribor, Slovenia, studying at the University of Ljubljana.</p><p>This site started years ago, back when I was more into web design — today it lives on as a portfolio and blog. If it feels like a joined effort between me from seven years ago and me today, that’s because it is.</p><p>I’m finishing my diploma and heading deeper into machine learning and data science, which is where most of my recent projects live.</p></div><div className="facts"><span>Slovenia</span><span>Machine learning</span><span>Data science</span><span>Creative coding</span></div></section>
  <section className="section"><div className="section-heading"><div><SectionLabel>Selected work</SectionLabel><h2>Recent projects</h2></div><Link to="/blog" className="text-link">All posts →</Link></div><div className="featured-grid">{featured.map((post, index) => <Link to={`/blog/${post.slug}`} className="featured-card" key={post.slug}><div><b>0{index + 1}</b><time>{new Date(post.date).getFullYear()}</time></div><h3>{post.title}</h3><small>{post.tags.slice(0, 2).join(' · ')}</small></Link>)}</div></section>
</> }
function Blog() { return <section className="page section"><SectionLabel>Writing &amp; projects</SectionLabel><h1>Things I’ve built</h1><p className="lede">A running log of projects from the past few years — machine learning experiments, graphics engines, and the odd weekend hack.</p><div className="post-list">{posts.map((post, index) => <Link className="post-row" to={`/blog/${post.slug}`} key={post.slug}><img src={post.image} alt="" /><div><div className="post-meta"><span>{String(index + 1).padStart(2, '0')}</span><time>{formatDate(post.date)}</time>{post.wip && <em>WIP</em>}</div><h2>{post.title}</h2><p>{post.description}</p><small>{post.tags.join('  /  ')}</small></div><strong>↗</strong></Link>)}</div></section> }
function Post() { const { slug } = useParams(); const post = postBySlug(slug); if (!post) return <section className="section page"><h1>Post not found</h1><Link to="/blog">Back to blog</Link></section>; const Content = post.Content; return <article className="article section narrow"><Link className="back" to="/blog">← All posts</Link><div className="article-meta">{formatDate(post.date)} · {post.tags.join(' / ')}</div><h1>{post.title}</h1><p className="lede">{post.description}</p>{post.image && <img className="article-cover" src={post.image} alt="" />}<Content DemoFrame={DemoFrame} /></article> }
function Portfolio() { const groups = { Languages: ['Python', 'JavaScript', 'Java', 'SQL'], Tools: ['PyTorch', 'pandas', 'Git', 'Firebase'], Focus: ['Machine learning', 'Data science', 'Graphics'], Interests: ['Visualization', 'Algorithms', 'Web'] }; return <section className="page section"><SectionLabel>Portfolio</SectionLabel><h1>What I bring to the table</h1><p className="lede">A snapshot of my skills and background — the full CV is below. There are smaller competitions and projects I’d happily talk through in person.</p><div className="skills">{Object.entries(groups).map(([name, items]) => <div key={name}><SectionLabel>{name}</SectionLabel>{items.map(item => <span key={item}>{item}</span>)}</div>)}</div><div className="info-grid"><div><SectionLabel>Education</SectionLabel><h3>University of Ljubljana</h3><p>B.Sc. Computer Science — finishing my diploma, focused on machine learning and data science.</p></div><div><SectionLabel>Beyond the blog</SectionLabel><p>A lot of PyTorch and data-science work — CNNs, image recognition, and coursework around AI and data processing — that doesn’t always warrant a full post but adds up to a solid grounding in the field.</p></div></div><div className="section-heading cv-heading"><div><SectionLabel>Curriculum vitae</SectionLabel><h2>The full CV</h2></div><div className="actions"><a className="button button-primary" href="/CV.pdf" target="_blank" rel="noreferrer">Open PDF ↗</a><a className="button" href="mailto:sevcnikar.lan@gmail.com">Email me</a></div></div><object className="cv" data="/CV.pdf#toolbar=0&view=FitH" type="application/pdf"><a href="/CV.pdf">Open CV PDF</a></object></section> }
export default function App() { return <Layout><Routes><Route path="/" element={<Home />} /><Route path="/blog" element={<Blog />} /><Route path="/blog/:slug" element={<Post />} /><Route path="/portfolio" element={<Portfolio />} /><Route path="*" element={<Home />} /></Routes></Layout> }
